spring:
  application:
    name: twid

logging:
  level:
    io.lw900925.twid: debug

twi:
  twitter:
    access-token: Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA
    cookie: _ga=GA1.2.355978636.1696834840; _gid=GA1.2.412823723.1696834840; external_referer=padhuUp37zjgzgv1mFWxJ5Xq0CLV%2BbpWuS41v6lN3QU%3D|0|8e8t2xd8A2w%3D; guest_id=v1%3A169683483879780232; _twitter_sess=BAh7CSIKZmxhc2hJQzonQWN0aW9uQ29udHJvbGxlcjo6Rmxhc2g6OkZsYXNo%250ASGFzaHsABjoKQHVzZWR7ADoPY3JlYXRlZF9hdGwrCMfpPBOLAToMY3NyZl9p%250AZCIlOWY2ZGZmMWEwZjQxM2U3NTk5YTQ5YWYzZWU0ZDhlYjc6B2lkIiViMjc3%250AOGJlZGI2MTA4ODRiMGMzMzZkODA5MzNiNmFmNA%253D%253D--1a7c6d7c1d3707f7495eb14332b0f060683c3494; kdt=XPOvppS070xH0WksXNSfkdA8tktyDu1QG6NMQVac; auth_token=4378760532335661354e9908ec6715256b9ae718; ct0=b4a3332efb60287b63f2032aa6c06d2d1578bb2d66e0bafe4704f3e8031558ffddb099c3c5377d63275316130f7a308ac1d4ceaf6f8d88a29b7280a9f494794030a5ed31b589c79c809326954e6b6534; att=1-zPWw0H6tLNmVJ9gMzINzfnC1HTRpCuarggXWdR3A; guest_id_ads=v1%3A169683483879780232; guest_id_marketing=v1%3A169683483879780232; twid=u%3D1130422335251464193; personalization_id="v1_xM6VrGFSyIFSh2SJEMWwEg=="
    api:
      media:
        url: https://api.twitter.com/graphql/YcKL-v9RI2t42QCEDfv-9g/UserMedia
        param: classpath:param/media.json
      user_info:
        url: https://twitter.com/i/api/graphql/Vf8si2dfZ1zmah8ePYPjDQ/UserByScreenNameWithoutResults
        param: classpath:param/user_info.json
    proxy:
      host: 127.0.0.1
      port: 7890
      username:
      password:
  list: ${user.dir}/config/list.txt
  cache: ${user.dir}/cache/timeline_id.json
  location: ${user.dir}/downloads
